# Generated by Django 4.0.4 on 2022-05-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0002_connection'),
    ]

    operations = [
        migrations.CreateModel(
            name='XmlFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Имя файла')),
                ('file', models.FileField(upload_to='scheme/xml', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Xml файл',
                'verbose_name_plural': 'Xml файлы',
            },
        ),
    ]
