# Generated by Django 4.0.4 on 2022-05-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0003_xmlfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationshipsTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Связь терминов')),
                ('therm_id1', models.IntegerField(verbose_name='id первого термина')),
                ('therm_id2', models.IntegerField(verbose_name='id второго термина')),
                ('connection_id', models.IntegerField(verbose_name='id связи')),
            ],
            options={
                'verbose_name': 'Связь терминов',
                'verbose_name_plural': 'Связи терминов',
            },
        ),
    ]
